### ISSUE TITLE
Issue using @babel/eslint-parser

### ISSUE THREAD

**Issue by IgorNovikov10** [asbjornh/view-models#17] opened 2022-05-29 17:39 UTC
When running Linter and using syntax like this 
https://gyazo.com/6bcf845196aedf7900ae71c4e8eb29f7 I get such errors 
https://gyazo.com/f334f03a3669c988924abf1f1c569efe . For some models, I exclude properties from the generated models (using 'ignore' attribute), however, the @babel/eslint-parser highlights this syntax with an error, what can be the reason for such a behavior?

Just run the 'yarn run lint:fix' in the root folder of the example attached in order to reproduce the problem.

I would appreciate any help from your side, thanks in advance
[ESLint-issue.zip](https://github.com/asbjornh/view-models/files/8793912/ESLint-issue.zip)

**Comment by asbjornh** [comment] 2022-05-29 21:27
Hey! Would you mind just pasting a code block with the problematic react component code here? Not a fan of downloading arbitrary zip files :)

**Comment by IgorNovikov10** [comment] 2022-05-30 06:27
yes, of course, here is an example of a component:

`import React from 'react';
import PropTypes from 'prop-types';
import cn from 'classnames';

const Breadcrumbs = ({
  links,
  className,
  lang = { ariaLabel: 'Breadcrumb' },
}) => {
  return (
    <>
      <nav className={cn('breadcrumbs', className)} aria-label={lang.ariaLabel}>
        {links && (
          <ol className="breadcrumbs__items">
            {links.map((link, i) => {
              const ariaCurrent = i === links.length - 1 ? 'page' : null;

              return null;
            })}
          </ol>
        )}
      </nav>
    </>
  );
};

Breadcrumbs.propTypes = {
  lang: PropTypes.shape({
    ariaLabel: PropTypes.string.isRequired,
  }).isRequired,
  className: PropTypes.string,
};

Breadcrumbs.viewModelMeta = {
  className: 'ignore',
};

export default Breadcrumbs;`

The problem is reproduced with node version 16.15.0 and @babel/eslint-parser as a Lint parser

**Comment by asbjornh** [comment] 2022-05-30 18:21
I'm not able to reproduce with the above code and node 16.15.0, `eslint@8.16.0`, `@babel/eslint-parser@7.18.2` and `@babel/preset-react@7.17.12`. Could you also post your babel config?

**Comment by IgorNovikov10** [comment] 2022-06-05 18:48
@asbjornh here is the link to the repository: https://github.com/IgorNovikov10/ESLint-issue

Just make sure you're running the project on the Node version 16.15.0, after that try run command `yarn run lint:fix`

**Comment by asbjornh** [comment] 2022-06-06 14:44
Hey! The repo has no eslint config file, so linting fails immediately. There's also no babel config file, which will probably also make it fail.

**Comment by IgorNovikov10** [comment] 2022-06-06 18:51
@asbjornh hey, sorry for that, I have updated the repo with the necessary files, thanks in advance!

**Comment by asbjornh** [comment] 2022-06-07 18:03
Thanks! I can reproduce now. It seems to be caused by `@babel` releasing breaking changes in a minor version. After upgrading `@babel` packages in `view-models` I can now reproduce this issue and a bunch of others.

I'll keep looking

**Comment by asbjornh** [comment] 2022-06-07 18:44
I've published a new version of `view-models` that should fix this issue. Let me know whether it solves the problem

**Comment by IgorNovikov10** [comment] 2022-06-07 19:34
hi @asbjornh the issue described above gone, thanks!

Have one more question, is oneOfType no longer allowed to be used?? https://gyazo.com/4da2b816cda22e3dba713eeb3119304a

**Comment by asbjornh** [comment] 2022-06-07 20:42
I'm not really sure what you mean. `oneOfType` has never been supported. The reason for this is that `oneOfType` can't be represented in C# (or couldn't at the time that this tool was created). `view-models` actually has tests that ensure that `oneOfType` gets reported as an error.

**Comment by IgorNovikov10** [comment] 2022-06-10 15:18
Thank you, got it. I have a few more questions:

1. When I set the paths in the options to be ignored by view-models https://gyazo.com/095a63d7e0b01be47e162dcde53254f7, the file that is located inside the specified folder is still checked by ESLint and I see an error from the view-models package https://gyazo.com/05b54e819095224c110ef3ff92c1e3ca, what could it be?

2. I have a component that extend prop types from another base component like this https://gyazo.com/f1abf2dea4d68679ad35c2df412cdcb0 while certain fields of this model are described and ignored through viewModelMeta https://gyazo.com/04c9d9bdc6f60ef67d33bbb46b5f0ef1 the plugin throws a warning and thinks prop types are not set https://gyazo.com/f2144684eea0712eb891d21231ec50d1 (if I'm not wrong). Is there any way to make it clear to the view-models plugin that there are prop types, and they are constructed from other prop types?

**Comment by IgorNovikov10** [comment] 2022-07-11 17:15
@asbjornh did you have a chance to take a look at the issues descibed above?

**Comment by IgorNovikov10** [comment] 2022-09-13 09:22
Hi @asbjornh just a friendly reminder, have you had a chance to check the issues above?

**Comment by asbjornh** [comment] 2022-09-13 14:18
1: That's the _Webpack plugin_ configuration. ESLint doesn't read your webpack config.
2: Probably a bug in the eslint plugin. You're welcome to report it as a separate issue. I'll look at it when/if I get the time or someone puts up a PR.

Closing this since the `@babel/eslint-parser` issue seems to be resolved

**Closed by asbjornh** 2022-09-13 14:18 UTC
